---
- name: Add nvidia repo (standard installation)
  when: edpm_nvidia_drivers_url == ""
  become: true
  ansible.builtin.yum_repository:
    name: nvidia-cuda-rhel
    description: NVIDIA CUDA repo for RHEL
    baseurl: "{{ edpm_nvidia_drivers_repo_url }}/$basearch/"
    gpgcheck: true
    gpgkey: "{{ edpm_nvidia_drivers_repo_url }}/$basearch/D42D0685.pub"

- name: Add nvidia repo (with exclusions for custom URL)
  when: edpm_nvidia_drivers_url != ""
  become: true
  ansible.builtin.yum_repository:
    name: nvidia-cuda-rhel
    description: NVIDIA CUDA repo for RHEL
    baseurl: "{{ edpm_nvidia_drivers_repo_url }}/$basearch/"
    gpgcheck: true
    gpgkey: "{{ edpm_nvidia_drivers_repo_url }}/$basearch/D42D0685.pub"
    exclude: nvidia-kmod-common

- name: Driver installation
  ansible.builtin.import_tasks: drivers.yaml

- name: Install Container Toolkit
  ansible.builtin.include_tasks: container_toolkit.yaml
  when: edpm_nvidia_drivers_install_container_toolkit | bool

- name: Install Management Library
  ansible.builtin.import_tasks: management_library.yaml
  when: edpm_nvidia_drivers_install_management_library | bool
