---
- name: Install NVIDIA Management Library RPM
  become: true
  ansible.builtin.dnf:
    name: libnvidia-ml
    state: present
  when: "'NVIDIA-vGPU-rhel-aie' not in ansible_facts.packages"  # The AIE driver includes the management library

