---
- name: Install NVIDIA Management Library RPM
  become: true
  ansible.builtin.dnf:
    name: libnvidia-ml
    state: present
  when: # The host driver RPMs include the management library
    - "'NVIDIA-vGPU-rhel-aie' not in ansible_facts.packages"
    - "'NVIDIA-vGPU-rhel' not in ansible_facts.packages"
