---
- name: Converge
  hosts: all
  roles:
    - role: "edpm_nvidia_drivers"
      vars:
        edpm_nvidia_drivers_install_container_tools: false
        edpm_nvidia_drivers_install_management_library: false
