---
- name: Converge
  hosts: all
  roles:
    - role: "edpm_nvidia_drivers"
      vars:
        edpm_nvidia_drivers_generate_cdi_config: false  # This can't be done without GPU hardware present
        edpm_nvidia_drivers_url: "file:///{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}/my-dummy.noarch.rpm"